name: CI

on: [push]

env:
  GITHUB_REF: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        set -x
        ls -l
        chmod a+x *.sh
        ./build.sh

    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: build
        retention-days: 1

  upload_release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/release-')
    needs: [build]

    steps:
      - name: Set Version
        run: |
          RELEASE="${GITHUB_REF/refs\/tags\/release-}"
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV

      - name: Note Release
        run: echo "Release is $RELEASE this time"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: plugin
          path: plugin

      - name: Check
        run: |
          set -x
          ls -lR
          OK_RELEASE=$( [ -f "plugin/plugin-$RELEASE.txt" ] && echo OK)
          echo "OK_RELEASE=$OK_RELEASE" >> $GITHUB_ENV

      - name: Release
        if: ${{ env.OK_RELEASE == 'OK' }}
        uses: ncipollo/release-action@v1
        with:
          token: $${{ secrets.GITHUB.TOKEN }}
          name: Release $${{ env.RELEASE }}
          allowUpdates: true
          prerelease: true
          artifacts: ${{ format('plugin/plugin-{0}.txt', env.RELEASE) }}
