name: CI

on: [push]

env:
  GITHUB_REF: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: |
        chmod a+x build.sh
        ./build.sh

    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: build
        retention-days: 1

  upload_release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/release-')
    needs: [build]

    steps:
      - name: Set Version
        run: |
          RELEASE="${GITHUB_REF/ref\/tags\/release-}"
          echo "::set-env name=RELEASE::$RELEASE"

      - name: Create Release
        run: echo "Release is $RELEASE this time"
